c_compiler_version:    # [osx]
  - 15                 # [osx]
cxx_compiler_version:  # [osx]
  - 15                 # [osx]
llvm_openmp:           # [osx]
  - 15                 # [osx]
c_stdlib_version:
  - 2.17               # [linux64]
  - 10.12              # [osx and x86]
